# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.20.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 832us/step - accuracy: 0.7930 - loss: 0.5330
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 795us/step - accuracy: 0.7960 - loss: 0.4769
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.7960 - loss: 0.4552
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7960 - loss: 0.4428
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7960 - loss: 0.4341
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7965 - loss: 0.4281
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.8152 - loss: 0.4241
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8219 - loss: 0.4210
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8238 - loss: 0.4183
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8245 - loss: 0.4163  
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8274 - loss: 0.4141 
Epoch 12/100
250/250

In [19]:
import joblib

joblib.dump(ann, "ann.pkl")


['ann.pkl']

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 200  205]]


0.8605

In [1]:
!git init

Initialized empty Git repository in C:/Users/Bunyod/Music/ANN/.git/


In [2]:
!git add .

In [3]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .ipynb_checkpoints/Artificial_neural_network-checkpoint.ipynb
	new file:   Artificial_neural_network.ipynb
	new file:   Churn_Modelling.csv



In [4]:
!git commit -m "first commit"

[master (root-commit) a4bc759] first commit
 3 files changed, 11737 insertions(+)
 create mode 100644 .ipynb_checkpoints/Artificial_neural_network-checkpoint.ipynb
 create mode 100644 Artificial_neural_network.ipynb
 create mode 100644 Churn_Modelling.csv


In [5]:
!git branch -M main

In [7]:
!git remote add origin https://github.com/machinelearnerr/ANN.git

In [8]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.


To https://github.com/machinelearnerr/ANN.git
 * [new branch]      main -> main


In [20]:
!git add "ann.pkl"

In [21]:
!git commit -m

error: switch `m' requires a value


In [22]:
! git commit -m "second commit"

[main 2fe4768] second commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 ann.pkl
